In [3]:
import pandas as pd

def f (x) :
  return x**6/6 - 3*x**4 - 2*x**3/3 + 27*x**2/2 + 18*x - 30

def d_f (x) :
  return x**5 - 12*x**3 - 2*x**2 +27*x + 18 # Complete this line with the derivative you have calculated.

x = -4.0

d = {"x" : [x], "f(x)": [f(x)]}
for i in range(0, 20):
  x = x - f(x) / d_f(x)
  d["x"].append(x)
  d["f(x)"].append(f(x))

pd.DataFrame(d, columns=['x', 'f(x)'])

           x          f(x)
0  -4.000000  7.133333e+01
1  -3.811287  1.223161e+01
2  -3.763093  6.515564e-01
3  -3.760224  2.198858e-03
4  -3.760214  2.531156e-08
5  -3.760214  1.421085e-13
6  -3.760214  4.263256e-14
7  -3.760214  4.263256e-14
8  -3.760214  4.263256e-14
9  -3.760214  4.263256e-14
10 -3.760214  4.263256e-14
11 -3.760214  4.263256e-14
12 -3.760214  4.263256e-14
13 -3.760214  4.263256e-14
14 -3.760214  4.263256e-14
15 -3.760214  4.263256e-14
16 -3.760214  4.263256e-14
17 -3.760214  4.263256e-14
18 -3.760214  4.263256e-14
19 -3.760214  4.263256e-14
20 -3.760214  4.263256e-14